assets: ["BTCUSDT", "ETHUSDT", "SOLUSDT"]
interval: "1h"
start_date: "2023-01-01"
end_date: "auto"           # "auto" usará la fecha actual
episodes: 600
save_freq: 1
max_restarts: 20
mixed_precision: true
