version: "3.9"

services:
  trading_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading_bot_container
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./results:/app/results
    environment:
      - TF_FORCE_GPU_ALLOW_GROWTH=true
      - TF_CPP_MIN_LOG_LEVEL=2
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]   # Si hay GPU, se usa automáticamente
    ports:
      - "6006:6006"  # (Opcional) puerto TensorBoard interno
    command: ["python3", "auto_train.py"]

  tensorboard:
    image: tensorflow/tensorflow:2.15.0
    container_name: tensorboard_drl
    command: tensorboard --logdir=/app/results --host=0.0.0.0
    ports:
      - "6007:6006"   # Abre TensorBoard en localhost:6007
    volumes:
      - ./results:/app/results
    depends_on:
      - trading_bot
