# El atributo `version` ya no es necesario en Compose V2, pero puedes dejarlo sin problema
services:
  trading_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading_bot_container
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./results:/app/results
    environment:
      - CUDA_VISIBLE_DEVICES=""       # Oculta las GPU a TensorFlow
      - TF_CPP_MIN_LOG_LEVEL=2        # Silencia logs innecesarios
    ports:
      - "6006:6006"                   # Puerto para TensorBoard interno (opcional)
    command: ["python3", "auto_train.py"]

  tensorboard:
    image: tensorflow/tensorflow:2.15.0
    container_name: tensorboard_drl
    command: tensorboard --logdir=/app/results --host=0.0.0.0
    ports:
      - "6007:6006"                   # Abre TensorBoard en localhost:6007
    volumes:
      - ./results:/app/results
    depends_on:
      - trading_bot
