services:
  trading_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading_bot_container
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./results:/app/results
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml          # ← Montamos el archivo de configuración
    environment:
      - CUDA_VISIBLE_DEVICES=                   # Fuerza TensorFlow a usar CPU
      - TF_CPP_MIN_LOG_LEVEL=2                  # Menos logs ruidosos
      - TF_ENABLE_ONEDNN_OPTS=0                 # ← evita los warnings numéricos
    ports:
      - "6006:6006"                             # TensorBoard interno
    command: ["sh", "-c", "exec python3 auto_train.py --no-gpu"]

  tensorboard:
    image: tensorflow/tensorflow:2.15.0
    container_name: tensorboard_drl
    command: tensorboard --logdir=/app/results --host=0.0.0.0
    ports:
      - "6007:6006"                             # Abre en http://localhost:6007
    volumes:
      - ./results:/app/results
    depends_on:
      - trading_bot
